# Generated by Django 5.0.2 on 2024-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hotel', 'available', 'number'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
