# Generated by Django 5.0.3 on 2024-03-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_options_alter_room_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
    ]
