# Generated by Django 5.0.2 on 2024-02-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_options_room_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time', 'creation_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
