# Generated by Django 5.0.3 on 2024-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='add_favors',
            field=models.ManyToManyField(to='booking.additionalfavor'),
        ),
    ]
